//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

@import UIKit;

@class ___FILEBASENAME___Router;
@class ___FILEBASENAME___Request;
@class ___FILEBASENAME___ViewModel;

@protocol ___FILEBASENAME___ViewControllerOutput <NSObject>
@required
- (void)doSomething:(___FILEBASENAME___Request *)request;
@end


@protocol ___FILEBASENAME___ViewControllerInput <NSObject>
@required
- (void)displaySomething:(___FILEBASENAME___ViewModel *)viewModel;
@end



@interface ___FILEBASENAME___ViewController : UIViewController <___FILEBASENAME___ViewControllerInput>

+ (instancetype)selfViewController;

@property (nonatomic) ___FILEBASENAME___Router *router;
@property (nonatomic) id<___FILEBASENAME___ViewControllerOutput> output;



@end

@interface ___FILEBASENAME___ViewController (Storyboard)
+ (instancetype)selfViewControllerWithStoryboardName:(NSString *)storyboardName;
@end
