//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

#import "___FILEBASENAME___Router.h"
#import "___FILEBASENAME___ViewController.h"

@interface ___FILEBASENAME___Router ()
@end

@implementation ___FILEBASENAME___Router

- (void)navigateToSomeWhere {
}

- (void)passDataToNextScene:(UIStoryboardSegue *)segue {
    // transition using segue
//    if ([segue.identifier isEqualToString:@"SampleScene"]) {
//        [self passDataToSomeWhereScene:segue];
//    }
}

- (void)passDataToSomeWhereScene:(UIStoryboardSegue *)segue {
//    NSLog(@"Function: %s, Line: %d", __PRETTY_FUNCTION__, __LINE__ );
}

- (void)transitionToNextScene {
    // programmatically create instance base on storyboard
    // SampleViewController *sample = [SampleViewController selfViewController];
    // ...
}


@end
