//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

#import "___FILEBASENAME___Interactor.h"
#import "___FILEBASENAME___Worker.h"
#import "___FILEBASENAME___Models.h"

@interface ___FILEBASENAME___Interactor ()

@end

@implementation ___FILEBASENAME___Interactor

- (void)doSomething:(___FILEBASENAME___Request *)request {
    
    // Do some works using request

    self.worker = [___FILEBASENAME___Worker new];
    [self.worker doSomeWork];
    
    
    ___FILEBASENAME___Response *response = [___FILEBASENAME___Response new];
    [self.output presentSomething:response];
}



@end
