//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

@import Foundation;

@class ___FILEBASENAME___Worker;
@class ___FILEBASENAME___Request;
@class ___FILEBASENAME___Response;

@protocol ___FILEBASENAME___InteractorOutput <NSObject>
@required
- (void)presentSomething:(___FILEBASENAME___Response *)response;
@end

@protocol ___FILEBASENAME___InteractorInput <NSObject>
@required
- (void)doSomething:(___FILEBASENAME___Request *)request;
@end

@interface ___FILEBASENAME___Interactor : NSObject <___FILEBASENAME___InteractorInput>
@property (nonatomic) id<___FILEBASENAME___InteractorOutput> output;
@property (nonatomic) ___FILEBASENAME___Worker *worker;
@end
