//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

@import Foundation;

@interface ___FILEBASENAME___Request : NSObject
@end

@interface ___FILEBASENAME___Response : NSObject
@end

@interface ___FILEBASENAME___ViewModel : NSObject
@end
