//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean ObjectiveC Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, base on http://clean-swift.com

#import "___FILEBASENAME___Presenter.h"
#import "___FILEBASENAME___Models.h"

@interface ___FILEBASENAME___Presenter ()

@end
@implementation ___FILEBASENAME___Presenter

- (void)presentSomething:(___FILEBASENAME___Response *)respnse {
    
    // TODO: get Response to viewModel
    ___FILEBASENAME___ViewModel *viewModel = [___FILEBASENAME___ViewModel new];
    [self.output displaySomething:viewModel];

}

@end
